---
# tasks file for drone

- name: install pip
  apt: name=python-pip cache_valid_time=86400 update_cache=yes

- name: install docker-py
  pip: name=docker-py version=0.3.0

- name: see if drone is already installed
  stat: path=/usr/local/bin/drone
  register: drone_stat

- name: ensure /etc/drone exists
  file: path=/etc/drone state=directory owner=root group=root mode=0700

- name: should drone be installed
  set_fact: install_drone={{ not drone_stat.stat.exists or upgrade_drone|default(False)|bool == True }}

- name: pull down latest deb file
  get_url: url=http://downloads.drone.io/latest/drone.deb dest=/tmp/drone.deb force={{ install_drone|default(False)|bool }}
  register: got_drone

- name: install drone
  command: dpkg --force-confdef --force-confold -i /tmp/drone.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  register: drone_dpkg
  when: install_drone|default(False)|bool
  notify:
    - restart drone

- name: Template SQL file for drone configuration
  template:
    src: drone.sql.j2
    dest: /etc/drone/drone.sql
    owner: root
    group: root
    mode: 0600
  register: drone_sql

- name: Install sqlite3 for drone configuration
  apt:
    name: sqlite3
    cache_valid_time: 86400
    update_cache: yes
  when: drone_driver == 'sqlite3'

- name: Hash tables to validate change
  shell: "sqlite3 /var/lib/drone/{{ drone_datasource }} 'SELECT * FROM users; SELECT * FROM settings;' | md5sum"
  register: drone_before_hash
  changed_when: False
  when: drone_driver == 'sqlite3'

- name: Configure drone settings
  shell: "sqlite3 /var/lib/drone/{{ drone_datasource }} '.read /etc/drone/drone.sql'"
  register: drone_after_hash
  changed_when: False
  when: drone_driver == 'sqlite3'

- name: Hash tables to validate change
  shell: "sqlite3 /var/lib/drone/{{ drone_datasource }} 'SELECT * FROM users; SELECT * FROM settings;' | md5sum"
  register: drone_after_hash
  changed_when: drone_after_hash.stdout != drone_before_hash.stdout
  when: drone_driver == 'sqlite3'

- name: ensure the drone user exists
  mysql_user: name={{ drone_mysql_user }} state=present password={{ drone_mysql_pass }} priv={{ drone_mysql_dbname}}.*:ALL
  when: drone_driver == 'mysql'

- name: ensure the drone database exists
  mysql_db: name={{ drone_mysql_dbname }} state=present
  when: drone_driver == 'mysql'

- name: Hash tables to validate change
  shell: "mysql -u {{ drone_mysql_user }} -p{{ drone_mysql_pass }} -h {{ drone_mysql_host }} {{ drone_mysql_dbname }} -e 'SELECT * FROM users; SELECT * FROM settings;' | md5sum"
  register: drone_before_hash
  changed_when: False
  when: drone_driver == 'mysql'

- name: configure drone settings
  mysql_db: name="{{ drone_mysql_dbname }}" state=import target=/etc/drone/drone.sql
  changed_when: False
  when: drone_driver == 'mysql'

- name: Hash tables to validate change
  shell: "mysql -u {{ drone_mysql_user }} -p{{ drone_mysql_pass }} -h {{ drone_mysql_host }} {{ drone_mysql_dbname }} -e 'SELECT * FROM users; SELECT * FROM settings;' | md5sum"
  register: drone_after_hash
  changed_when: drone_after_hash.stdout != drone_before_hash.stdout
  when: drone_driver == 'mysql'

- name: configure drone daemon
  template: src=default.j2 dest=/etc/default/drone owner=root group=root mode=0644
  notify:
    - restart drone

- name: setup ssl cert
  copy: src={{ drone_sslcert_file }} dest={{ drone_sslcert_location }} owner=root group=root mode=0644
  when: drone_scheme == 'https'

- name: setup ssl key
  copy: src={{ drone_sslkey_file }} dest={{ drone_sslkey_location }} owner=root group=root mode=0644
  when: drone_scheme == 'https'

- name: ensure drone is started
  service: name=drone state=started enabled=yes
